### ISSUE TITLE
Student having issues displaying output form js file from codepen

### ISSUE THREAD

**Issue by Enoch2k2** [learn-co-curriculum/selecting-single-elements-lab#10]
OS: Windows 7
Chrome Version: 58
issues:
selecting-single-elements-lab:170 Uncaught ReferenceError: $ is not defined at selecting-single-elements-lab:170
bqLqwL?type=embed&animations=run:40 GET https://s.codepen.io/joemburgess/fullembedgrid/lovelace.css 

bqLqwL?type=embed&animations=run:41 GET https://s.codepen.io/joemburgess/fullembedgrid/lovelace2.css 

VM2051 bqLqwL?type=embed&animations=run:40 GET https://s.codepen.io/joemburgess/fullembedgrid/lovelace.css 

VM2051 bqLqwL?type=embed&animations=run:41 GET https://s.codepen.io/joemburgess/fullembedgrid/lovelace2.css 

It seems like jquery for some reason isn't being loaded in this lesson when the student loads this lesson in the browser. It's worked for every other student and I haven't been able to find a solution for this.

He hasn't touched anything in the lesson coding wise.

Things we've tried:
Hard Reload and clear cache,
Tried importing jquery in the html of codepen
Tried selecting re run to see if it would work (error doesn't show up but output isn't displayed)

**Comment by gj** [comment]
Hey @Enoch2k2 !

Hard to diagnose what the problem was, but the lab's been updated quite a bit since then. If anything similar happens again, let me know!

Thanks 🙂
