### ISSUE TITLE
Selecting Single Elements 

### ISSUE THREAD

**Issue by sds800** [learn-co-curriculum/selecting-single-elements-lab#22]
just wanted to note, having an issue with the other two examples in this lesson, while the innerHTML attribute is working fine, the href and text attributes are returning errors in the codepen preview console

1st attachment is the working innerHTML attribute 
<img width="1646" alt="screen shot 2018-01-08 at 5 20 18 pm" src="https://user-images.githubusercontent.com/35237576/34695607-8ad0a6b8-f499-11e7-8d99-5cbd41ba27fc.png">

2nd is a null text attribute

<img width="1670" alt="screen shot 2018-01-08 at 5 21 27 pm" src="https://user-images.githubusercontent.com/35237576/34695615-93452008-f499-11e7-8726-80cec6b727b5.png">

**Comment by sgharms** [comment]
I think you might not _quite_ be fully understanding the way this code is
working. Try discussing your issue via the [Ask a Question][AAQ] tool. You're
close, so stick with it! I got it working. Check out your selector for `linkText` variable.

[AAQ]: http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson

**Comment by moseskalungi** [comment]
where do you get the linkText variable

**Comment by sgharms** [comment]
@moseskalungi You'll need to set the `linkText` variable by extracting the text from the correctly "targeted" DOM node. If you require help, don't hesitate to use Ask a Question
