### ISSUE TITLE
No Edit Button

### ISSUE THREAD

**Issue by hlmparks** [learn-co-curriculum/selecting-single-elements-lab#24]
I would like to submit some grammatical corrections as well as make some elaborations on the lab that I think could be helpful, but I do not have an Edit Button.

Thx,
-Heather

**Comment by sgharms** [comment]
@hlmparks You can `fork` this repository to your own account. You can then make edits on your *own* "fork." Once you're done you can "Open a Pull Request" and we'll have the ability to integrate your changes. That's part of the beauty of GitHub.
