### ISSUE TITLE
console.log not updating

### ISSUE THREAD

**Issue by richard-krakowski** [learn-co-curriculum/selecting-single-elements-lab#29]
I believe I've properly input the documentSelectors in this lab but the console.log is not updating. I want to make sure I get credit for the lesson.

<img width="554" alt="screen shot 2018-01-29 at 10 08 55 pm" src="https://user-images.githubusercontent.com/35939141/35546868-22bad312-0544-11e8-9cdc-e71b1c16a278.png">

<img width="525" alt="screen shot 2018-01-29 at 10 09 04 pm" src="https://user-images.githubusercontent.com/35939141/35546876-2c22e2b4-0544-11e8-9eb8-4a582cd48855.png">

**Comment by sgharms** [comment]
Hi! We've changed this lab to be a README only. We're not requiring you to submit code here. It was seriously confusing, sorry! Make sure you mark this as read and keep on going!
