### ISSUE TITLE
I feel dumb, but are we supposed to be doing everything off Learn.io OR Learn IDE

### ISSUE THREAD

**Issue by kotlowski** [learn-co-curriculum/selecting-single-elements-lab#4]

**Comment by gj** [comment]
Hey @kotlowski !

Definitely don't feel dumb — there are no stupid questions! 🙂 

For this lab, we're working entirely in the browser using the provided CodePen workspace coupled with [the Chrome JavaScript Console](https://developers.google.com/web/tools/chrome-devtools/console/), accessed via the `cmd-option-j` (Mac) or `ctrl-shift-j` (Windows/Linux) keyboard shortcut.

For other labs, however, you'll be using the Learn IDE. Every lesson should make it clear which environment it expects you to be using, but, if you ever feel lost, feel free to use [the Ask a Question feature](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) and our great Technical Coaches will get you back on track. 👍
