### ISSUE TITLE
Fork issue

### ISSUE THREAD

**Issue by myzenea** [learn-co-curriculum/selecting-single-elements-lab#41]
I have completed the lab and it will not allow me to fork the lab although it is saved and forked in GitHub

**Comment by maxwellbenton** [comment]
Hi @myzenea,

Sorry to hear you were having difficulty with this lab. If you are still working on any Learn lessons and continue to experience issues forking lessons, please reach out to support@learn.co for further assistance. [Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) is typically reserved for problems with the Learn.co curriculum content specific to this repository and we are unable to provide support for problems related to the Learn platform.

If you still feel that this is an issue with the curriculum, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thank you!
