### ISSUE TITLE
This website is under heavy load (queue full) We're sorry, too many people are accessing this website at the same time. We're working on this problem. Please try again later.

### ISSUE THREAD

**Issue by alexodiah** [learn-co-curriculum/selecting-single-elements-lab#49]
The below message keeps popping up with the Codepen.io link.
Please, what is the current status of this and is there anyway of getting around this.

This website is under heavy load (queue full)
We're sorry, too many people are accessing this website at the same time. We're working on this problem. Please try again later.

**Comment by Donnadieu** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
