### ISSUE TITLE
Mathematician link should begin with HTTP, not HTTPS

### ISSUE THREAD

**Issue by ivalentine** [learn-co-curriculum/selecting-single-elements-lab#8]
In the README, the mathematician link begins with HTTPS. However, on the Wikipedia page, the link begins with HTTP. Therefore, the link in the README should be changed to match this. This issue causes the second question to always fail, creating confusion among many students.

@jmburges The link on line 11 of [this CodePen](http://codepen.io/joemburgess/pen/bqLqwL) should start with `http`, not `https`.

Pull request forthcoming.

@aturkewi

**Comment by K1TCH** [comment]
I came here to say this.  It's still a problem.

If I'm not mistaken the correct answer should be: _document.querySelector('p a').href_

which returns "http://s.codepen.io/wiki/Mathematician"

but it compares to "https://s.codepen.io/wiki/Mathematician"

**Comment by gj** [comment]
Fixed: https://github.com/learn-co-curriculum/selecting-single-elements-lab/commit/6958b3c92ab12a18dafdc4bb2c8d314f96ffa3b0

Thanks for reporting!
